### ISSUE TITLE
It Wont Work

### ISSUE THREAD

**Issue by GJJBEWORK** [cppshane/Background-Terminal#15]
I Got It To Download And Install but When It Shows Up On My Desktop It Wont Let Me Type Commands But It Thinks The Text At The Start Is A Textbox But When I try To Type Nothing Happens I Tested 64 Bit Version And 32 Bit Please Fix This.

![image](https://github.com/user-attachments/assets/da32aa86-c942-4d9e-b0f3-7f0eb7a43a3b)

**Comment by SomewhatAwake** [comment]
bit of info here:
seems to be a .net error:
`Application: Background-Terminal.exe
CoreCLR Version: 4.700.22.41602
.NET Core Version: 3.1.29
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at Background_Terminal.MainWindow.<>c__DisplayClass29_0.<.ctor>b__1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Background_Terminal.MainWindow.<.ctor>b__29_0(Object o, NotifyCollectionChangedEventArgs target)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Background_Terminal.MainWindow.ErrorDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`
